docs(sending-message): sending message c4 diagrams
pagopa/io-messages pull request #20
Opened 2024-09-04 09:46 UTC by acuiuli

#### List of Changes

- [docs(sending-message): add message-sender system diagram](https://github.com/pagopa/io-messages/commit/08e7d58ef1b1c9ce100414ce0912ce420f34a1d2)
- [docs(sending-message): add fn-services component diagram](https://github.com/pagopa/io-messages/commit/1b9deb0325e02355d62a28f9179f9167cea272a1)

#### Motivation and Context

Added 2 c4 diagrams to describe how a message is sent. One diagram is a container diagram of the message-sender  system and the other is a component diagram of the sending message functionality of io-fn-services.

#### How Has This Been Tested?

No tests are needed, just documentaions

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-09-04 14:21 UTC, Garma00 commented on docs/sending-message/fn-services.plantuml
> +
I would add the queue with failed process messages so we can highlight that the OnFailedProcessMessage is triggered by this queue.

2024-09-04 14:23 UTC, Garma00 commented
Also, we have a discusion [here](https://github.com/pagopa/io-messages/pull/18#issuecomment-2326201718) on naming convention for components on those diagrams

2024-09-09 15:17 UTC, lucacavallaro requested changes

2024-09-09 15:17 UTC, lucacavallaro commented on docs/sending-message/fn-services.plantuml
> +!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml
```suggestion
!include <C4/C4_Context>
```

2024-09-09 15:17 UTC, lucacavallaro commented on docs/sending-message/fn-services.plantuml
> +title Component diagram for io-function-services
What is the actual system we are modeling? It seems that the scope is broader than `io-function-services`

2024-09-09 15:17 UTC, lucacavallaro commented on docs/sending-message/fn-services.plantuml
> +Container_Boundary(io-fn-services, "io-fn-services") {
Are you sure that `services` is the right boundary?

2024-09-11 09:14 UTC, acuiuli commented on docs/sending-message/fn-services.plantuml
> +title Component diagram for io-function-services
We are modeling the `io-function-services` container using a component diagram. There are also the interactions of the `io-function-services `container with external system/container

2024-09-16 13:00 UTC, acuiuli commented on docs/sending-message/fn-services.plantuml
> +
this has been fixed [here](https://github.com/pagopa/io-messages/pull/20/commits/c8b2c54c0f6feac9b3092c2a61efd7484b7a4166)

2024-09-17 08:36 UTC, Garma00 approved these changes

2024-09-19 14:56 UTC, lucacavallaro approved these changes

2024-09-19 14:57 UTC, merged