feat: added action group io_com_error to functions
pagopa/io-messages pull request #30
Opened 2024-09-12 15:30 UTC by acuiuli

#### List of Changes

- [added new action group io_com_error](https://github.com/pagopa/io-messages/commit/4a88ce531ca203bcb41d02bc537d1e614df611f0)

#### Motivation and Context

This pr add a the new action group io_com_error for monitoring purposes

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-09-12 15:34 UTC, lucacavallaro requested changes

2024-09-12 15:34 UTC, lucacavallaro commented on infra/resources/_modules/function_app_citizen/variables.tf
> +variable "io_com_error_id" {
we don't need to be specific here

```suggestion
variable "action_group_id" {
```

2024-09-16 10:41 UTC, Garma00 approved these changes

2024-09-16 10:42 UTC, lucacavallaro approved these changes

2024-09-16 10:49 UTC, merged