feat(etl-func): init setup etl-func and health check
pagopa/io-messages pull request #39
Opened 2024-09-24 15:35 UTC by acuiuli

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-09-25 12:50 UTC, lucacavallaro commented
tf config missing

2024-09-25 12:51 UTC, lucacavallaro requested changes
tf config missing

2024-09-25 13:58 UTC, lucacavallaro requested changes

2024-09-25 13:58 UTC, lucacavallaro commented on apps/etl-func/src/adapters/env.ts
> +  .and(z.record(z.string(), z.string()));
I would remove it since it is not used right now

2024-09-25 13:58 UTC, lucacavallaro commented on apps/etl-func/src/adapters/config.ts
> +}
```suggestion
// TODO(IOCOM-1786): move this function in "io-messages-common"
export async function loadConfigFromEnvironment(
  onSuccess: (config: Config) => Promise<void>,
) {
  try {
    const config = configFromEnvironment.parse(process.env);
    await onSuccess(config);
  } catch (err) {
    if (err instanceof ZodError) {
      err.issues.forEach((issue) => {
        logger.error({ issue }, "Error parsing environment variable");
      });
    } else if (err instanceof Error) {
      logger.error(
        {
          err,
        },
        err.message,
      );
    } else {
      logger.error(
        {
          err,
        },
        "Unable to start the application due to an unexpected error",
      );
    }
  }
}
```

2024-09-25 14:58 UTC, Garma00 requested changes

2024-09-25 14:58 UTC, Garma00 commented on apps/etl-func/host.json
> +    "version": "[3.*, 4.0.0)"
```suggestion
    "version": "[4.*, 5.0.0)"
```

2024-09-25 14:58 UTC, Garma00 commented on apps/etl-func/package.json
> +    "@pagopa/handler-kit-azure-func": "^2.0.3",
Do we need those dependencies? We do not plan to use fp-ts

2024-09-25 15:05 UTC, acuiuli commented on apps/etl-func/src/adapters/env.ts
> +  .and(z.record(z.string(), z.string()));
Do you mean removing the entire file or just the env variable and leave the object empty?

2024-09-30 07:56 UTC, lucacavallaro commented on apps/etl-func/src/adapters/env.ts
> +  .and(z.record(z.string(), z.string()));
remove the env variable, since that is not used

2024-09-30 15:12 UTC, Garma00 approved these changes

2024-10-01 07:59 UTC, lucacavallaro requested changes

2024-10-01 07:59 UTC, lucacavallaro commented on .github/workflows/etl-func-deploy.yaml
> +    uses: pagopa/dx/.github/workflows/web_app_deploy.yaml@add-web-app-deploy-workflow
```suggestion
    uses: pagopa/dx/.github/workflows/web_app_deploy.yaml@b7a84bd876d31797ac87daf9cefebd8f6a579c08
```

2024-10-01 07:59 UTC, lucacavallaro commented on .github/workflows/etl-func-deploy.yaml
> +      use_staging_slot: false
```suggestion
      use_staging_slot: true
```

2024-10-01 07:59 UTC, lucacavallaro commented on apps/etl-func/src/adapters/config.ts
> +        connectionString: env.APPLICATIONINSIGHTS_CONNECTION_STRING,
since `APPLICATIONINSIGHTS_CONNECTION_STRING` was removed, it should also removed here

2024-10-01 07:59 UTC, lucacavallaro commented on apps/etl-func/src/adapters/config.ts
> +    connectionString: z.string().min(1),
since `APPLICATIONINSIGHTS_CONNECTION_STRING` was removed, it should also removed here

2024-10-01 07:59 UTC, lucacavallaro commented on infra/resources/_modules/web_apps/functions_etl.tf
> +  source = "github.com/pagopa/dx//infra/modules/azure_function_app?ref=f339355788f12e5e4719159dca45d7c0b5c0c537"
```suggestion
  source = "github.com/pagopa/dx//infra/modules/azure_function_app?ref=b7a84bd876d31797ac87daf9cefebd8f6a579c08"
```

2024-10-01 07:59 UTC, lucacavallaro commented on infra/resources/_modules/web_apps/functions_etl.tf
> +  tier = "test"
```suggestion
  tier = "m"
```

we can safely use the `m` size for this function

2024-10-01 07:59 UTC, lucacavallaro commented on infra/resources/_modules/web_apps/functions_etl.tf
> +  application_insights_sampling_percentage = 100
we should stick to default (that should be `5`, maybe)

2024-10-02 15:38 UTC, Garma00 commented on infra/resources/_modules/web_apps/functions_etl.tf
> +output "function_app_messages_sending" {
why `funciton_app_messages_sending`?

2024-10-02 15:40 UTC, acuiuli commented on infra/resources/_modules/web_apps/functions_etl.tf
> +output "function_app_messages_sending" {
You are right, it's a typo

2024-10-02 16:05 UTC, lucacavallaro approved these changes

2024-10-02 16:06 UTC, merged