adding read messages c4 diagrams
pagopa/io-messages pull request #41
Opened 2024-09-26 12:38 UTC by lucamancosu

#### List of Changes

- [adding read messages c4 diagrams](https://github.com/pagopa/io-messages/commit/b6cc1bb943903fd28a2f256948c2e2c2e9bb5d20)

#### Motivation and Context

Added two c4 diagrams to describe the read message system. The message-list-reader diagram shows how a cityzen can retrieve the message list and which are the system involved components. The mobile-app diagram shows the interactions between the cityzen and the mobile application and the relatad mobile components.

#### How Has This Been Tested?

No tests are needed, just documentaions

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-09-26 12:58 UTC, Garma00 requested changes

2024-09-26 12:58 UTC, Garma00 commented on docs/read-messages/message-list-reader.plantuml
> +Person(customer, Cittadino, "Someone in the team working on an issue or component")
```suggestion
Person(customer, Citizen, "Someone in the team working on an issue or component")
```

2024-09-26 12:58 UTC, Garma00 commented on docs/read-messages/mobile-app.plantuml
> +Person(customer, Cittadino, "Someone in the team working on an issue or component")
```suggestion
Person(customer, Citizen, "Someone in the team working on an issue or component")
```

2024-09-27 07:40 UTC, Garma00 approved these changes
GJ

2024-10-02 08:31 UTC, Garma00 commented
I think we can merge this cc @lucacavallaro @acuiuli

2024-10-02 08:51 UTC, acuiuli approved these changes

2024-10-08 13:36 UTC, merged