making loadConfigFromEnvironment a common package
pagopa/io-messages pull request #48
Opened 2024-10-04 08:11 UTC by lucamancosu

#### List of Changes

Created a new workspace io-messages-common. The loadConfigFromEnvironment function is now a common package. 
#### Motivation and Context

Avoid code dupplication
#### How Has This Been Tested?

1. root of the project, execute: yarn install
2.  root of the project, execute: yarn build
3. go inside the apps/notif-func and create a local.settings.json
4. if you put the mandatory env var inside the local.settings.json and run the yarn start command the function starts correctly
5. if you DONT put the mandatory env var inside the local.settings.json and run the yarn start command the function returns an error and a logging of the missing variables
6. Unit tests have been written

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-10-04 10:19 UTC, Garma00 requested changes
Well done, just some small changes 💯

2024-10-04 10:19 UTC, Garma00 commented on packages/io-messages-common/package.json
> +    "io-ts": "^2.2.21",
Do we need `io-ts` as dependency here?

2024-10-04 10:19 UTC, Garma00 commented on packages/io-messages-common/src/adapters/tests/index.spec.ts
> +    await expect(functionEntryPoint).toHaveBeenCalledOnce();
We do not need to `await` here, also if you remove those 2` await` yo can remove the `async` in the it callback as well.
If you agree you can make the same changes to the other tests 😄

2024-10-04 10:27 UTC, lucamancosu commented on packages/io-messages-common/src/adapters/tests/index.spec.ts
> +    await expect(functionEntryPoint).toHaveBeenCalledOnce();
loadConfigFromEnvironment is an async function. I think we must await to test how it resolves. We are awaiting for its execution in the functions codebase too. Can you explain why i must remove the await and if you can propose a way to test it without awaiting ?

2024-10-04 10:28 UTC, lucamancosu commented on packages/io-messages-common/package.json
> +    "io-ts": "^2.2.21",
no needed

2024-10-04 10:52 UTC, Garma00 commented on packages/io-messages-common/src/adapters/tests/index.spec.ts
> +    await expect(functionEntryPoint).toHaveBeenCalledOnce();
You are right but here you are using `.resolves` which is a property of `Assertion<Promise<void>>`
![immagine](https://github.com/user-attachments/assets/167a94bc-5e20-47f1-9d5e-b0906961e0f3)

2024-10-07 14:41 UTC, lucacavallaro commented on packages/io-messages-common/src/adapters/tests/index.spec.ts
> +    await expect(functionEntryPoint).toHaveBeenCalledOnce();
@Garma00, @lucamancosu is right, we need `await` here even if we use `resolves`

> If the assertion is not awaited, then you will have a false-positive test that will  pass every time. To make sure that assertions are actually called, you may use [expect.assertions(number)](https://vitest.dev/api/expect.html#expect-assertions).

https://vitest.dev/api/expect.html#resolves

2024-10-07 15:13 UTC, Garma00 commented on packages/io-messages-common/src/adapters/tests/index.spec.ts
> +    await expect(functionEntryPoint).toHaveBeenCalledOnce();
Ok sorry for the confusion, my bad!

2024-10-09 15:27 UTC, Garma00 commented on packages/io-messages-common/src/adapters/tests/index.spec.ts
> +    await expect(functionEntryPoint).toHaveBeenCalledOnce();
Sorry for reopening this thread, I just realised that you are both right on the `await` that we are using on `resolves`, on the other hand the `await` used on `toHaveBeenCalled` is not needed (also ts-server states this)
![image](https://github.com/user-attachments/assets/7c82bbb9-71ce-49d7-8dd2-80db0c7f396c)
@lucacavallaro @lucamancosu

2024-10-09 15:54 UTC, lucamancosu commented on packages/io-messages-common/src/adapters/tests/index.spec.ts
> +    await expect(functionEntryPoint).toHaveBeenCalledOnce();
@Garma00 you're right. Changes already pushed

2024-10-14 07:24 UTC, Garma00 approved these changes

2024-10-16 10:15 UTC, merged