feat: add transformMessage method
pagopa/io-messages pull request #58
Opened 2024-11-08 10:55 UTC by Garma00

#### List of Changes

* Add a method that transform the result of the `extractMessage` method into a valid type for the `loadMessage` method;

#### Motivation and Context

We need to transform the output before loading it.

#### How Has This Been Tested?

Unit test.

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] My changes does not requires change to the documentation,

2024-11-08 14:43 UTC, lucacavallaro requested changes

2024-11-08 14:43 UTC, lucacavallaro commented on apps/etl-func/src/adapters/message.ts
> +  getMessageEventFromMessage({
imho this should be a **pure** function unrelated to `Message` class

`Message` should not be aware of `MessageEvent` 😄

2024-11-11 09:11 UTC, Garma00 commented on apps/etl-func/src/adapters/message.ts
> +  getMessageEventFromMessage({
Yess you are right, take a look here [5529dcf](https://github.com/pagopa/io-messages/pull/58/commits/5529dcf7a32c8ed41aac111efe5569703a63f4c0) 😄

2024-11-11 09:17 UTC, Garma00 commented on apps/etl-func/src/domain/message.ts
> +  isPending: z.boolean(),
@lucacavallaro as we discussed I removed the `optional` flag from isPending.
The function that calls `getMessageByMetadata` method will be responsible for ensuring that `isPending` is defined.

2024-11-12 14:34 UTC, lucacavallaro requested changes

2024-11-12 14:34 UTC, lucacavallaro commented on apps/etl-func/src/adapters/message.ts
> +}: Message): MessageEvent => ({
add `messageEventSchema.parse`

2024-11-12 14:34 UTC, lucacavallaro commented on apps/etl-func/src/adapters/message.ts
> +  schema_version: 1,
`.default(1)`

2024-11-15 13:49 UTC, lucacavallaro approved these changes

2024-11-15 14:04 UTC, merged